services:
  - type: web
    name: github-dev-card
    env: docker
    region: ohio
    plan: free
    dockerContext: .
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: ENV
        value: production
